# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
# - devel 
### WARNING about vignette.rds on R-devel
### => http://r.789695.n4.nabble.com/R-CMD-build-then-check-fails-on-R-devel-due-to-serialization-version-td4747582.html

warnings_are_errors: true
