# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel

warnings_are_errors: true
